export const carsData = [
  // {
  //   id: 1,
  //   price: 285000000,
  //   photo: '../../../assets/img/car1.webp',
  //   name: 'Ford Explorer 3.5 Xlt',
  //   km: '53.100 Km',
  //   brand: 'Ford',
  //   model: '2016',
  //   plate: 'LKP299',
  //   ubication: 'Usaquen-Bogotá D.C.',
  //   viewCount: 20,
  // },
  // {
  //   id: 2,
  //   price: 185000000,
  //   photo: '../../../assets/img/car1.webp',
  //   name: 'Ford Explorer 3.5 Xlt',
  //   km: '53.100 Km',
  //   brand: 'Ford',
  //   model: '2016',
  //   plate: 'LKP299',
  //   ubication: 'Usaquen-Bogotá D.C.',
  //   viewCount: 15,
  // },
  // {
  //   id: 3,
  //   price: 9000000,
  //   photo: '../../../assets/img/car1.webp',
  //   name: 'Ford Explorer 3.5 Xlt',
  //   km: '53.100 Km',
  //   brand: 'Ford',
  //   model: '2016',
  //   plate: 'LKP299',
  //   ubication: 'Usaquen-Bogotá D.C.',
  //   viewCount: 40,
  // },
  // {
  //   id: 4,
  //   price: 15000000,
  //   photo: '../../../assets/img/car1.webp',
  //   name: 'Ford Explorer 3.5 Xlt',
  //   km: '53.100 Km',
  //   brand: 'Ford',
  //   model: '2016',
  //   plate: 'LKP299',
  //   ubication: 'Usaquen-Bogotá D.C.',
  //   viewCount: 200,
  // },
  // {
  //   id: 5,
  //   price: 1000000,
  //   photo: '../../../assets/img/car1.webp',
  //   name: 'Ford Explorer 3.5 Xlt',
  //   km: '53.100 Km',
  //   brand: 'Ford',
  //   model: '2016',
  //   plate: 'LKP299',
  //   ubication: 'Usaquen-Bogotá D.C.',
  //   viewCount: 100,
  // },
  // {
  //   id: 6,
  //   price: 400000,
  //   photo: '../../../assets/img/car1.webp',
  //   name: 'Ford Explorer 3.5 Xlt',
  //   km: '53.100 Km',
  //   brand: 'Ford',
  //   model: '2016',
  //   plate: 'LKP299',
  //   ubication: 'Usaquen-Bogotá D.C.',
  //   viewCount: 30,
  // },
  // {
  //   id: 7,
  //   price: 7000000,
  //   photo: '../../../assets/img/car1.webp',
  //   name: 'Ford Explorer 3.5 Xlt',
  //   km: '53.100 Km',
  //   brand: 'Ford',
  //   model: '2016',
  //   plate: 'LKP299',
  //   ubication: 'Usaquen-Bogotá D.C.',
  //   viewCount: 1,
  // },
  // {
  //   id: 8,
  //   price: 15000000,
  //   photo: '../../../assets/img/car1.webp',
  //   name: 'Ford Explorer 3.5 Xlt',
  //   km: '53.100 Km',
  //   brand: 'Ford',
  //   model: '2016',
  //   plate: 'LKP299',
  //   ubication: 'Usaquen-Bogotá D.C.',
  //   viewCount: 19,
  // },
  // {
  //   id: 9,
  //   price: 65000000,
  //   photo: '../../../assets/img/car1.webp',
  //   name: 'Ford Explorer 3.5 Xlt',
  //   km: '53.100 Km',
  //   brand: 'Ford',
  //   model: '2016',
  //   plate: 'LKP299',
  //   ubication: 'Usaquen-Bogotá D.C.',
  //   viewCount: 2,
  // },
];
